### ISSUE TITLE
Install Failure

### ISSUE THREAD

**Issue by yuedeji** [dyninst/toolchain-origin#1]
Hi, great work! I want to install origin on my desktop but failed. My desktop is a Ubuntu 14.04 x64 machine. The errors I met are missing files as shown below.

feature.cpp:33:32: fatal error: InstructionDecoder.h: No such file or directory
#include "InstructionDecoder.h"

Seems like origin has dependencies not included in the file. Could you provide an integrity version which will have a huge impact.

**Comment by mxz297** [comment]
I am sorry that the README file is quite incomplete. In your case, you will need to download and install Dyninst first, which should be the only additional dependency, which is accessible at https://github.com/dyninst/dyninst

**Comment by yuedeji** [comment]
Hi, thanks for your answer. I have installed Dyninst, but I still got the same error. I also put the origin folder under the Dyninst folder.

**Comment by yuedeji** [comment]
Hi, I modified the Makefile under function-feature to include the related libraries. However, I got another error. Could you please take a look if you have time.

g++ -L/usr/local/lib -L/usr/lib -L/usr/lib -L/usr/local/lib  -o extractFeat feature.o idiom.o operand.o lookup.o extractFeat.o graphlet.o supergraph.o colors.o FeatureAnalyzer.o IdiomAnalyzer.o GraphletAnalyzer.o -lparseAPI -linstructionAPI -ldwarf -lsymtabAPI -ldynDwarf -ldynElf -lelf -lcommon  
/usr/bin/ld: warning: libdw.so.1, needed by /usr/local/lib/libsymtabAPI.so, not found (try using -rpath or -rpath-link)
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_formstring@ELFUTILS_0.122'
/usr/local/lib/libdynDwarf.so: undefined reference to `dwarf_cfi_addrframe@ELFUTILS_0.142'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_offdie@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_linebeginstatement@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_getlocations@ELFUTILS_0.157'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_onesrcline@ELFUTILS_0.122'
/usr/local/lib/libdynDwarf.so: undefined reference to `dwarf_begin_elf@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_attr@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_formref_die@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_dieoffset@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_onearange@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_child@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_getaranges@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_lowpc@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_getcfi_elf@ELFUTILS_0.142'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_highpc@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_getsrcfiles@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_formsdata@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_getarangeinfo@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_siblingof@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_formaddr@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_offdie_types@ELFUTILS_0.148'
/usr/local/lib/libdynDwarf.so: undefined reference to `dwarf_frame_info@ELFUTILS_0.142'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_getelf@ELFUTILS_0.126'
/usr/local/lib/libdynDwarf.so: undefined reference to `dwarf_getcfi@ELFUTILS_0.142'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_lineaddr@ELFUTILS_0.122'
/usr/local/lib/libdynDwarf.so: undefined reference to `dwarf_frame_register@ELFUTILS_0.142'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_hasform@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_tag@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_lineno@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_filesrc@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_addrdie@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_diename@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_hasattr@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_linecol@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_errmsg@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_next_cfi@ELFUTILS_0.142'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_linesrc@ELFUTILS_0.122'
/usr/local/lib/libdynDwarf.so: undefined reference to `dwarf_frame_cfa@ELFUTILS_0.142'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_next_unit@ELFUTILS_0.148'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_hasattr_integrate@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_formudata@ELFUTILS_0.122'
/usr/local/lib/libdynDwarf.so: undefined reference to `dwarf_end@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_lineendsequence@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_ranges@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_getsrclines@ELFUTILS_0.122'
/usr/local/lib/libsymtabAPI.so: undefined reference to `dwarf_nextcu@ELFUTILS_0.122'
collect2: error: ld returned 1 exit status
make: *** [extractFeat] Error 1

**Comment by mxz297** [comment]
I just push a new commit, which changes the makefile and add a little bit more explanation on how to install. I test it with latest Dyninst and you should be able to install it now.

Still, the steps of using it is not written yet. I will try complete it in these days.

**Comment by yuedeji** [comment]
Hi, Xiaozhu, thanks for your work. But I still face the problem I mentioned above. I wonder is it possible for you to share a runnable Virtual Machine or a docker environment?

**Comment by mxz297** [comment]
Please make sure that you pull my latest commit. Dyninst recently has a dependency change from libdwarf to libdw. The error message you posted shows that you compile with libdwarf. If you update the makefile, you should not see the same problem.

**Comment by yuedeji** [comment]
I see! I installed libdw-dev and the problem was solved finally. Thank you so much for answering my questions!
