### ISSUE TITLE
./install.sh meet error "feature.h:38:28: fatal error: Operation_impl.h: No such file or directory"

### ISSUE THREAD

**Issue by island255** [dyninst/toolchain-origin#2]
Hi, I am trying to build the environment based on a docker _gauravtripathi/dyninst_. But I meet the following errors:

In file included from feature.cpp:39:0:
feature.h:38:28: fatal error: Operation_impl.h: No such file or directory
 #include "Operation_impl.h"
                            ^
compilation terminated.
make: *** [feature.o] Error 1

Can you help me to solve this problem?

**Comment by mxz297** [comment]
I am not sure who created `gauravtripathi/dyninst`, but it looks like it does not use a recent version of Dyninst. File `Operation_impl.h` was introduced in Dyninst 10.0.

**Comment by island255** [comment]
Thanks for your reply. I tried with Dyninst 10.1 and built it without error.
